#!/usr/bin/env bash

# Enable the bell for this script
xset b

if [ -z "$@" ]; then
    echo -ne "\a"
else
    for ((i=0; i<$1; i++))
    do
    	echo -ne "\a"
	sleep .2
    done
fi

# Disable the bell again
xset -b
