#!/usr/bin/env bash

. ~/.bashrc --silent

# TODO: check to see if the required binary exists! Optionally, install it.

if [ ! -f "$1" ] ; then
    echo "$ALERT '$1' is not a valid file"
    return $false
fi

case "$1" in

    map install_if_dne tar bzip2 unrar gzip unzip uncompress p7zip

    *.tar.bz2) tar xvjf "$1" ;;
    *.tar.gz)  tar xvzf "$1" ;;
    *.bz2)     bunzip2 "$1" ;;
    *.rar)     unrar x "$1" ;;
    *.gz)      gunzip "$1" ;;
    *.tar)     tar xvf "$1" ;;
    *.tbz2)    tar xvjf "$1" ;;
    *.tgz)     tar xvzf "$1" ;;
    *.zip)     unzip "$1" ;;
    *.Z)       uncompress "$1" ;;
    *.7z)      7z x "$1" ;;

    *)  echo -ne "$ALERT '$1' cannot be extracted via"
	echo -ne "${BOLD}$FUNCNAME${Color_Off}"
    	return 1 ;;
esac; echo

function install_if_dne() {
    [[ $(which $1) ]] || yes | sudo pacman -S $1
}
