#!/bin/bash

# Here we trap the control c interrupt to avoid leaving behind
# sensitive information
function ctrl-c() {
    for file in ${sensitive} ; do
	shred -uz ${file%.gpg}
    done
    echo
}
trap ctrl-c SIGINT

# Variables
mutt="mutt"
sensitive=$(cat<<EOF
$HOME/.netrc.gpg
$HOME/.msmtprc.gpg
$HOME/.mutt/.mutt.passwords.gpg
$HOME/.imapfilter/config.lua.gpg
EOF
)

# obtain password
read -p "Password: " -s passwd
echo

# Decrypt files
pushd $HOME/.mutt 2>/dev/null
for file in ${sensitive} ; do
    gpg --batch -q --passphrase=${passwd} -o ${file%.gpg} -d ${file} 2>/dev/null
    chmod 600 ${file%.gpg} 2>/dev/null
done

# Run target
export LOCAL_CONFIG='esc'
${mutt}

ctrl-c
