#!/usr/bin/ruby

# Created by Eric Crosson Thursday June 13, 2013 12:24 PM

if ARGV.size != 2 && ARGV.size != 3
  puts "Usage: rprint [number to convert] [new base] <old base>"
  puts "       <old base> defaults to 10"
  exit
end

old = 10
old = ARGV[2] if ARGV.size == 3

puts ARGV[0].to_i(old.to_i).to_s(ARGV[1].to_i).upcase
