#!/bin/bash

# $1= host in human readable form

# Vars
unset rfbauth
host_key="Host $1"
config=$HOME/.ssh/config
vnc_config=$HOME/Dropbox/config/vnc/config
host=`grep -A1 "$host_key" $config | grep -i Hostname | cut -d' ' -f2`
rfbauth=`grep -A2 "$host_key" $vnc_config | grep -i rfbauth | cut -d' ' -f2`

# If a password is specified, then we need to include it in the call to vncviewer
[[ !($rfbauth && -e $rfbauth) ]] && vncpasswd # give the user a chance to never have to do this again

rfbauth="-passwd ${rfbauth}"

vncviewer $rfbauth $host &2>/dev/null &
