#!/bin/bash

unset driver
interface=$(ip addr | grep -o "wlp[[:alnum:]]*")

case $interface in
    wlp*) driver=wext ;;
    *)    driver=n180211 ;;
esac

# Only start wpa_supplicant if it doesn't have a lock yet
[[ -d /var/run/wpa_supplicant ]] || \
    (sudo wpa_supplicant -B -c/etc/wpa_supplicant.conf -D${driver} -i${interface} && \
    sudo iwconfig ${interface} power off)

# Wait for stability
while [[ -z $(ps -e | grep wpa_supplicant) ]]; do
    sleep 1
done
sleep 1				# one more for good measure

[[ $(ps -e | grep dhcpcd) ]] || sudo dhcpcd ${interface} -S domain_name_servers=8.8.8.8
