#!/bin/bash

while [[ $1 ]]; do
    case $1 in

	-h|--help)
	    cat<<EOF
`basename $0`: A script to activate wifi and connect to the internet.

Note: be sure rfkill is not activated.

Possible arguments are as follows

         --help
         -h       Display this help information. `basename $0` has no man page.
EOF
	    exit $EXIT_HELP
	    ;;
    esac
    shift
done

unset driver
source $HOME/.bashrc --silent
interface=$(wi)

case $interface in
    wlp*) driver=wext ;;
    *)    driver=n180211 ;;
esac

# Only start wpa_supplicant if it doesn't have a lock yet
[[ -d /var/run/wpa_supplicant ]] || \
    (sudo wpa_supplicant -B -c/etc/wpa_supplicant.conf -D${driver} -i${interface} && \
    sudo iwconfig ${interface} power off)

# Wait for stability
while [[ -z $(ps -e | grep wpa_supplicant) ]]; do
    sleep 1
done
sleep 1				# one more for good measure

[[ $(ps -e | grep dhcpcd) ]] || sudo dhcpcd ${interface} -S domain_name_servers=8.8.8.8
